# How to securely add secret/password in your playbook
---

  - hosts: webservers

    vars_files:
      - passwords-vault.yml
      
    become: true
    tasks:
      - name: Get password to connect to DB
        debug: 
          msg: "{{ db_password }}"
        